'use client'
import type { Metadata } from "next";
import * as React from 'react';
import { Inter } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { ThemeProvider } from '@mui/material/styles';
import theme from "@/theme";
import ResponsiveAppBar from "./_components/navbar/page";
import {Provider} from 'react-redux';
import {store} from '@/lib/store'
import { Toaster } from "react-hot-toast";


const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-body ${inter.className}`}>
        <Provider store={store}>
      <ResponsiveAppBar/>
      <AppRouterCacheProvider>
      <ThemeProvider theme={theme}>
      <Toaster
      position="top-right"
      containerStyle={{ top: 50, right: 50 }}
      toastOptions={{
        duration: 8000,
      }}
       />
        {children}
        </ThemeProvider>
        </AppRouterCacheProvider>
        </Provider>
      </body>
    </html>
  );
}
// className={inter.className}